server:
  servlet:
    context-path: /prodhub
  port: 8081
  shutdown: graceful  

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    enabled: true

spring:
  data:
    mongodb:
      host: 10.128.0.2
      port: 27017
      database: prodhub
      pool:
        max-wait-queue-size: 1000
        min-size: 5
        max-size: 20
        max-life-time: 1000
        max-wait-time: 30
        maintenance-initial-delay: 1000
        maintenance-frequency: 1000
        max-connection-idle-time: 5
  kafka:
    bootstrap-servers: 10.128.0.2:29092
    topic:
      buildStatus: buildStatus
      deploymentConfigAndSubmit: deployment-config-and-submit
      deploymentUpdates: deployment-update
      ephemeralEnvironmentUpdate: ephemeral-environment-update
      deploymentSetStatusUpdate: deploymentSet-status-update
      ephemeralEnvironmentBuildAndDeployment: ephemeral-environment-build-and-deployment
      buildStatusComplete: buildStatusComplete
      buildUpdate: build_update
      pipeline-execution: pipeline-execution
      pipeline-execution-update: pipeline-execution-update
      releaseCandidate: release_candidate

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

vault:
  uri: http://10.128.0.2:8200
  token:

cicaptain:
  uri: http://cicaptain.cicaptain.svc.cluster.local/ci-captain
  triggerBuildPath: /api/v1/pipeline-executions/trigger
  buildStatus: /api/v1/providers/%s/job/%s/status
  default:
    provider:
      id: default-provider

deplorch:
  uri: http://cloudedgedeloyer.cloudedgedeloyer.svc.cluster.local/cloudedge-deployer
  initiateDeployment: /api/v1/deployment/start
  deployedPodDetails: /api/v1/pods
  initiatePipelineDeployment: /api/v1/pipeline/deployment

cron:
  codeFreezeScheduler: "15 * * * * *"
  ephemeralCleanup: "15 * * * * *"

github:
  baseURL: https://github.com
